version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@vercel/ncc"
    versions:
    - 0.28.0
    - 0.28.1
    - 0.28.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
